#database
spring:
  datasource:
#    druid:
#    okboss:
    url: jdbc:mysql://localhost:3306/okboss?setUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: okboss88888
#      okbossbbs:
#        url: jdbc:mysql://localhost:3306/okbossbbs?setUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        username: root
#        password: okboss88888