server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8
#database
spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
  jackson:
    default-property-inclusion: non_null # null值不返回
    date-format: yyyy-MM-dd HH:mm:ss

#druid多数据源影响，mybatis plus配置在运行时加载，见MybatisPlusConfig.java
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    db-config:
      # 主键策略
      #id-type: auto
      # 表名前缀
      table-prefix: t_
      # 表名是否使用下划线间隔，默认：是
      #table-underline: true
    banner: false
  # 添加mybatis配置文件路径
  #config-location: mybatis-config.xml
  # 配置实体类包地址
  type-aliases-package: com.kk.api.**.mapper
  configuration:
    # 驼峰转下划线
    map-underscore-to-camel-case: true
    default-fetch-size: 500
    default-statement-timeout: 80
logging:
  file:
    path: logs
